import Head from "next/head";
import { Navbar } from "../components";
import shared from "../shared.json";

const Index = () => {
  return (
    <>
      <Head>
        <title>{`${shared.name} - ${shared.description}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  );
};

export default Index;
