import type { NextPage } from "next";
import Head from "next/head";
import shared from "../shared.json";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{`${shared.name}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
