import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import shared from "../shared.json";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{`${shared.name}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
    </div>
  );
};

export default Home;
